### ISSUE TITLE
waydroid configuration and uninstallation

### ISSUE THREAD

**Issue by itsnotsaved** [n1lby73/waydroid-installer#2]
1. I ran waydroid-installer on ubuntu 22.04 x11 gnome and after the installation completed; i saw terminal has printed that i need switch to wayland and a new window appeared called "policy tool" (java?). I closed it and tried to launch waydroid but it doesn't open
2. After the device restart, i saw (netstat -tulpn) it listen to the port 53; and i can't start local dns server docker instance due that reason ([adguardhome](https://hub.docker.com/r/adguard/adguardhome)). how to fix that problem? i don't want stop use dns server because of this tool. 
`tcp        0      0 192.168.240.1:53        0.0.0.0:*               LISTEN `
(Also, this has a bridge interface same as for anbox but it doesn't have such problem)
3. Uninstall (add to readme for reinstall or completely remove purposes)
How to uninstall waydroid and its all contents installed by waydroid installer? or what're them to uninstall manually? (one by one) (i mean packages, leftover files, folders and settings such as net interfaces etc)

**Comment by n1lby73** [comment]
can you provide waydroid log to know what the issue really is, and also the script only tells you that if your window manager/display server  is not Wayland which you can easily switch since you are on Ubuntu

and I'll run the uninstaller and make necessary commit

**Comment by itsnotsaved** [comment]
>also the script only tells you that if your window manager/display server is not Wayland which you can easily switch since you are on Ubuntu

No, i don't want to use it because some languages keyboards (input sources) do not work with it

>and I'll run the uninstaller and make necessary commit

https://github.com/n1lby73/waydroid-installer/blob/main/unistall.sh

Fix the file name: uninstall

I ran the uninstaller but it doesn't work

```
sudo sh unistall.sh 
unistall.sh: 3: [[: not found
-e [+] Stopping waydroid session
[11:47:23] WayDroid session is not started
unistall.sh: 11: [[: not found
-e [+] SCript has failed due to some unknwn error
```

(Note: i didn't remove any part of waydroid but  when i start PC, I kill the process that listen on port 53 to start the dns server)
sudo lsof -i TCP:53 -> sudo kill -9 <process>

>can you provide waydroid log to know what the issue really is

I'll give you after reinstall

**Comment by n1lby73** [comment]
uninstaller is fixed

**Comment by n1lby73** [comment]
> Since you've requested it would be added to debian soon as i would like to fix the error with the uninstaller

Added....kindly close the issue if you think it has been resolved

**Comment by itsnotsaved** [comment]
Check the readme https://github.com/n1lby73/waydroid-installer and fix 

waydroidd-installer --> waydroid-installer

```
  git clone https://github.com/n1lby73/waydroidd-installer
  cd waydroid-installer
  chmod +x *
  ./requirements.sh
  ```
  
  sorry, i was busy. i like to  install this tool again but i need to solve below problem. waydroid run a own dnsmasq and listen to the port 53
  
>2. After the device restart, i saw (netstat -tulpn) it listen to the port 53; and i can't start local dns server docker instance due that reason ([adguardhome](https://hub.docker.com/r/adguard/adguardhome)). how to fix that problem? i don't want stop use dns server because of this tool.
tcp 0 0 192.168.240.1:53 0.0.0.0:* LISTEN

**Comment by n1lby73** [comment]
It not a thing 

> sorry, i was busy. i like to install this tool again but i need to solve below problem. waydroid run a own dnsmasq and listen to the port 53

It not a thing with the tool buh waydroid it self......I guess there might be some config you'll have to change or fix up ......you can meet up the team in the [discussion forum ](https://t.me/WayDroid)

**Comment by n1lby73** [comment]
> waydroidd-installer --> waydroid-installer
> 
> ```
> 
> ```

Fixed and thanks for notifying me
